export const productos = [
  {
    id: 1,
    nombre: 'Producto 1',
    codigo: 'P001',
    categoria: 'Electrónica',
    stock: 15,
    stockMinimo: 5,
    precioUnitario: 25.00,
    precioPorMayor: 22.00,
    precioPreferencial: 20.00,
    costoAdquisicion: 15.00,
    enConsigna: false,
    descripcion: 'Producto de alta calidad',
    foto: 'producto1.jpg',
    fechaCreacion: '2025-03-24T12:00:00',
    activo: true
  },
  {
    id: 2,
    nombre: 'Producto 2',
    codigo: 'P002',
    categoria: 'Muebles',
    stock: 8,
    stockMinimo: 5,
    precioUnitario: 30.00,
    precioPorMayor: 28.00,
    precioPreferencial: 25.00,
    costoAdquisicion: 20.00,
    enConsigna: true,
    descripcion: 'Mueble elegante y cómodo',
    foto: 'producto2.jpg',
    fechaCreacion: '2025-03-24T12:00:00',
    activo: true
  },
  {
    id: 3,
    nombre: 'Producto 3',
    codigo: 'P003',
    categoria: 'Ropa',
    stock: 22,
    stockMinimo: 5,
    precioUnitario: 15.50,
    precioPorMayor: 13.00,
    precioPreferencial: 12.00,
    costoAdquisicion: 10.00,
    enConsigna: false,
    descripcion: 'Ropa de buena calidad',
    foto: 'producto3.jpg',
    fechaCreacion: '2025-03-24T12:00:00',
    activo: true
  },
  {
    id: 4,
    nombre: 'Producto 4',
    codigo: 'P004',
    categoria: 'Herramientas',
    stock: 10,
    stockMinimo: 5,
    precioUnitario: 20.00,
    precioPorMayor: 18.00,
    precioPreferencial: 16.00,
    costoAdquisicion: 12.00,
    enConsigna: false,
    descripcion: 'Herramienta profesional',
    foto: 'producto4.jpg',
    fechaCreacion: '2025-03-24T12:00:00',
    activo: true
  },
  {
    id: 5,
    nombre: 'Producto 5',
    codigo: 'P005',
    categoria: 'Electrónica',
    stock: 5,
    stockMinimo: 5,
    precioUnitario: 35.00,
    precioPorMayor: 32.00,
    precioPreferencial: 30.00,
    costoAdquisicion: 25.00,
    enConsigna: false,
    descripcion: 'Producto tecnológico avanzado',
    foto: 'producto5.jpg',
    fechaCreacion: '2025-03-24T12:00:00',
    activo: true
  },
  {
    id: 6,
    nombre: 'Producto 6',
    codigo: 'P006',
    categoria: 'Electrónica',
    stock: 30,
    stockMinimo: 5,
    precioUnitario: 18.00,
    precioPorMayor: 16.00,
    precioPreferencial: 14.00,
    costoAdquisicion: 10.00,
    enConsigna: false,
    descripcion: 'Producto electrónico accesible',
    foto: 'producto6.jpg',
    fechaCreacion: '2025-03-24T12:00:00',
    activo: true
  },
  {
    id: 7,
    nombre: 'Producto 7',
    codigo: 'P007',
    categoria: 'Electrónica',
    stock: 25,
    stockMinimo: 5,
    precioUnitario: 40.00,
    precioPorMayor: 36.00,
    precioPreferencial: 32.00,
    costoAdquisicion: 30.00,
    enConsigna: false,
    descripcion: 'Producto premium',
    foto: 'producto7.jpg',
    fechaCreacion: '2025-03-24T12:00:00',
    activo: true
  },
];
